services:
  database-postgresql:
    image: postgres:16-alpine3.17
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=surveys
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: elestio/pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - "8080:8080"

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database-postgresql
    ports:
      - "8000:8000"
    command: sh -c "php artisan migrate && php -S 0.0.0.0:8000 -t public"

volumes:
  postgresql-data:
